### ISSUE TITLE
(Off-Topic) Taiga.sh Compromised?

### ISSUE THREAD

**Issue by Grunet** [FujiMakoto/saucebot#16]
(This issue isn't related to this repo, I just wasn't sure how else to contact you)

**Describe the bug**
Navigating to taiga.sh redirects me to allowandgo.com, which appears to be a notification-based scam as far as I can tell

**To Reproduce**
1. In any browser navigate to taiga.sh
2. Notice that it redirects to allowandgo.com, displaying something like the screenshot below
    - Sometimes it will automatically redirect to google.com after a little bit too (not sure why, doesn't seem browser/private mode specific or anything)

**Expected behavior**
Navigate to the site itself

**Screenshots**
![image](https://user-images.githubusercontent.com/29322882/106408374-ed122180-6403-11eb-8924-6e6dbc2665b6.png)

**Additional context**
It was hard to figure out how to get a hold of you through the Twitter bot's account alone

**Comment by Grunet** [comment]
(Sorry for the double spam depending on your notification prefs) @FujiMakoto

**Comment by FujiMakoto** [comment]
@Grunet Genuinely thank you so much for reporting this, this was a major oversight on my part not properly hardening permissions and keeping Laravel dependencies up-to-date.

More likely I'm guessing there may have been a security bug in one of the included demo PHP scripts these bootstrap templates like to include, so I've gone ahead and nuked all of those and removed the malicious code from all relevant files, and properly hardened permissions on everything to permit it from happening again.
